 
import "./globals.css";
import { Web3Provider } from "./context/Web3Context";
 

export const metadata = {
  title: "Vote App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Web3Provider>
          
        {children}
        </Web3Provider>
      </body>
    </html>
  );
}
