import "./globals.css";
import { Web3Provider } from "./context/Web3Context";

export const metadata = {
  title: "Vote App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-br from-gray-800 to-slate-900 text-white overflow-hidden  ">
        <Web3Provider>
          <div className="p-2s">{children}</div>
        </Web3Provider>
      </body>
    </html>
  );
}
